// Translation data
const translations = {
    de: {
        "head.title": "BIOBUILDS Gesamtkatalog 2026",
        "cover.vertical_text": "Aus der Natur geboren, fürs Leben gebaut",
        "brand.name": "BIOBUILDS",
        "brand.module_label": "BIOBUILDS MODULAR",
        "cover.h1_line1": "Mehr als ein Haus",
        "cover.h1_line2": "eine Lebensweise",
        "cover.tagline": "Nachhaltiges Wohnen neu definiert",
        "year.2026": "2026",
        "contact.email": "hello@biobuilds.com",
        "contact.domain": "biobuilds.com",
        "page_label.PAGE 1": "SEITE 1",
        "p1.h2": "Von der Natur zur Exzellenz",
        "p1.intro": "Unser 386-mm-Wandsystem verbindet nachhaltige Materialien mit modernster Technik und erreicht herausragende Wärmeleistung und Luftdichtheit in einem natürlichen Wohnumfeld.",
        "spec.steico.title": "STEICO Holzfaser",
        "spec.steico.desc": "300 mm natürliche Holzfaser-Ultra-Dämmung.",
        "spec.membrane.title": "Smart-Membran",
        "spec.membrane.desc": "Dampfdiffusionsoffene Schicht, damit die Wände 'atmen' können.",
        "spec.osb.title": "ECO-OSB aus Deutschland",
        "spec.osb.desc": "Formaldehydfrei für ein gesundes Raumklima",
        "spec.structure.title": "Zertifizierte Tragstruktur",
        "spec.structure.desc": "Patentierte C24-Holzrahmenstruktur, zertifiziert vom Passivhaus Institut",
        "alt.epd_logo": "EPD-Zertifizierung",
        "alt.passivhaus_logo": "Passivhaus-Zertifikat",
        "alt.wall_section": "Wandaufbau-Diagramm",
        "page_label.PAGE 2": "SEITE 2",
        "p2.title": "AUSBAUHAUS",
        "p2.subtitle": "BIOBUILDS Ausbauhaus: Sie sind der Designer. Außen komplett fertig, innen bereit für Ihre Gestaltung.",
        "p2.section.interior": "Innen",
        "p2.interior.item1": "MODULAR™ Struktur ~35 cm, Passivhaus / EPD zertifiziert. Volumetrisches Timber-Frame-System mit SteicoFLEX-Dämmung, Holzfaser-Außenbeplankung, intelligenter Membran und durchgehender OSB-Ebene. Keine Wärmebrücken. Vollständig luftdicht.",
        "p2.interior.item2": "Abgedichtete Badezimmer mit fertigen Installationen",
        "p2.interior.item3": "Bereit für Ihr individuelles Design und Ihre Oberflächen",
        "p2.section.exterior": "Außen",
        "p2.exterior.lead": "Außen vollständig fertiggestellt:",
        "p2.exterior.item1": "Passivhaus-zertifizierte Struktur: MODULAR",
        "p2.exterior.item2": "Natürliche Yakisugi/Lunawood-Fassade",
        "p2.exterior.item3": "Be- und entlüftetes Flachdach mit EPDM-Membran",
        "p2.exterior.item4": "Integriertes Regenwassersammelsystem",
        "p2.exterior.item5": "Dreifachverglaste Fenster, Aluminiumrahmen Genesis 90",
        "p2.section.installations": "Installationen",
        "p2.installations.item1": "Komplette Elektrovorrüstung (EU-weit konform)",
        "p2.installations.item2": "Komplette Sanitärvorrüstung (EU-weit konform)",
        "p2.installations.item3": "Küchenanschlüsse vorbereitet (bereit für Möbel und Geräte)",
        "p2.section.docs": "Dokumentation",
        "p2.docs.item1": "Passivhaus-Zertifizierung",
        "p2.docs.item2": "EPD-Nachhaltigkeitsdokumentation",
        "p2.docs.item3": "CE-Kennzeichnung aller relevanten Komponenten",
        "p2.docs.item4": "24 Monate Garantie (privat), 12 Monate (gewerblich)",
        "page_label.PAGE 3": "SEITE 3",
        "p3.title": "SCHLÜSSELFERTIG",
        "p3.subtitle": "Alles inklusive, von außen bis innen, smarte Systeme und mehr.",
        "p3.section.interior": "Innen",
        "p3.interior.lead": "Alles aus dem Ausbauhaus plus:",
        "p3.interior.item1": "Natürliche Holzlamellendecken mit Recycling-Filz",
        "p3.interior.item2": "Wandoberflächen aus unserem Katalog: Glasfasergewebe, Filz, Holzfurnier usw.",
        "p3.interior.item3": "Dreischicht-Holzparkett 9–14 mm, FSC-zertifiziert, strapazierfähige Oberfläche",
        "p3.interior.item4": "S10-Wabenkern-Innentüren (CE-zertifiziert)",
        "p3.interior.item5": "Schneider Premium-Steckdosen (CE/VDE-zertifiziert)",
        "p3.section.exterior": "Außen",
        "p3.exterior.lead": "Außen vollständig fertiggestellt:",
        "p3.exterior.item1": "Passivhaus-zertifizierte Struktur: MODULAR",
        "p3.exterior.item2": "Organische Yakisugi/Lunawood-Fassade",
        "p3.exterior.item3": "Be- und entlüftetes Flachdach mit EPDM-Membran",
        "p3.exterior.item4": "Integriertes Regenwassersammelsystem",
        "p3.exterior.item5": "Dreifachverglaste Fenster, Aluminiumrahmen Genesis 90",
        "p3.section.installations": "Installationen",
        "p3.installations.lead": "Alles aus dem Ausbauhaus PLUS:",
        "p3.installations.item1": "Schlüsselfertiges Bad: Mineralwerkstein-Fliesen, italienisches Becken, Grohe-Wand-WC, Walk-in-Dusche",
        "p3.installations.item2": "Ariston Velis Warmwasserspeicher (ultraflaches Design)",
        "p3.installations.item3": "Smart-Beleuchtung (Philips HUE oder IKEA TRÅDFRI)",
        "p3.installations.item4": "Smarte Außenjalousien",
        "p3.installations.item5": "Zehnder Lüftung + Panasonic Wärmepumpe",
        "p3.section.docs": "Dokumentation",
        "p3.docs.item1": "Passivhaus-Zertifizierung",
        "p3.docs.item2": "EPD-Nachhaltigkeits-Dokumentation",
        "p3.docs.item3": "CE-Kennzeichnung aller relevanten Komponenten",
        "p3.docs.item4": "24 Monate Garantie (privat), 12 Monate (gewerblich)",
        "page_label.PAGE 4": "SEITE 4",
        "house.nest": "NEST",
        "alt.nest_ext": "NEST 24 m² Außenansicht",
        "alt.nest_int": "NEST 24 m² Innenansicht",
        "page_label.PAGE 5": "SEITE 5",
        "p5.title": "NEST",
        "p5.subtitle_short": "24 m² • 1 Schlafzimmer",
        "p5.subtitle_long_line1": "Das Tiny-House-Konzept, komplett neu gedacht.",
        "p5.subtitle_long_line2": "Ideal für Tourismus oder einen minimalistischen, zeitgemäßen Lebensstil.",
        "price.label.semi": "Ausbauhaus",
        "price.label.turnkey": "Schlüsselfertig",
        "price.value.nest.semi": "39.800 €",
        "price.value.nest.turnkey": "59.800 €",
        "alt.floorplan_24": "Grundriss 24 m²",
        "dims.title": "Abmessungen",
        "dims.label.bedroom": "Schlafzimmer",
        "dims.label.bathroom": "Badezimmer",
        "dims.label.interior": "Innenmaß",
        "dims.label.exterior": "Außenmaß",
        "dims.value.nest.bedroom": "14,20 m²",
        "dims.value.nest.bathroom": "3,45 m²",
        "dims.value.nest.interior": "5,70 m × 3,10 m × 2,50 m",
        "dims.value.nest.exterior": "6,40 m × 3,80 m × 3,20 m",
        "page_label.PAGE 6": "SEITE 6",
        "upgrades.title": "UPGRADES",
        "finish.cashmere": "Cashmere",
        "finish.hazelnut": "Hazelnut",
        "finish.price.nest.cashmere.semi": "Ausbauhaus: 1.800 €",
        "finish.price.nest.cashmere.tk": "Schlüsselfertig: Inklusive",
        "finish.price.nest.hazelnut.semi": "Ausbauhaus: 1.800 €",
        "finish.price.nest.hazelnut.tk": "Schlüsselfertig: Inklusive",
        "cladding.yakisugi": "Yakisugi",
        "cladding.lunawood": "Lunawood",
        "cladding.choose": "Wunschfassade wählen",
        "upgrade.ventilation": "Lüftungsanlage",
        "upgrade.blinds": "Smarte Jalousien",
        "upgrade.solar": "Solar-Kit Null-Energie",
        "upgrade.price.nest.ventilation.semi": "Ausbauhaus: 4.800 €",
        "upgrade.price.nest.ventilation.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.nest.blinds.semi": "Ausbauhaus: 2.000 €",
        "upgrade.price.nest.blinds.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.nest.solar": "7.800 €",
        "upgrade.note.solar": "Erzeugt 60 % mehr Energie als der jährliche Verbrauch",
        "upgrade.ventilation.disclaimer": "Lüftungsanlage von Zehnder variiert je nach Modulgröße",
        "page_label.PAGE 7": "SEITE 7",
        "house.wanderlust": "WANDERLUST",
        "alt.wanderlust_ext": "WANDERLUST 48 m² Außenansicht",
        "alt.wanderlust_int": "WANDERLUST 48 m² Innenansicht",
        "page_label.PAGE 8": "SEITE 8",
        "p8.title": "WANDERLUST",
        "p8.subtitle_short": "48 m² • 1 Schlafzimmer",
        "p8.subtitle_long": "Perfekt für Paare oder als Feriendomizil. Komfort und Effizienz in einem durchdachten Raum.",
        "price.value.wanderlust.semi": "59.800 €",
        "price.value.wanderlust.turnkey": "109.800 €",
        "alt.floorplan_48": "Grundriss 48 m²",
        "dims.label.living_kitchen": "Wohnen + Küche",
        "dims.value.wanderlust.living_kitchen": "19,90 m²",
        "dims.value.wanderlust.bedroom": "11,80 m²",
        "dims.value.wanderlust.bathroom": "4,50 m²",
        "dims.value.wanderlust.interior": "11,60 m × 3,10 m × 2,50 m",
        "dims.value.wanderlust.exterior": "12,40 m × 3,80 m × 3,20 m",
        "page_label.PAGE 9": "SEITE 9",
        "finish.price.wanderlust.cashmere.semi": "Ausbauhaus: 3.800 €",
        "finish.price.wanderlust.cashmere.tk": "Schlüsselfertig: Inklusive",
        "finish.price.wanderlust.hazelnut.semi": "Ausbauhaus: 3.800 €",
        "finish.price.wanderlust.hazelnut.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.wanderlust.ventilation.semi": "Ausbauhaus: 7.800 €",
        "upgrade.price.wanderlust.ventilation.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.wanderlust.blinds.semi": "Ausbauhaus: 4.000 €",
        "upgrade.price.wanderlust.blinds.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.wanderlust.solar": "11.800 €",
        "upgrade.note.wanderlust.solar": "Erzeugt 60 % mehr Energie als der jährliche Verbrauch",
        "page_label.PAGE 10": "SEITE 10",
        "house.serenity": "SERENITY",
        "alt.serenity_ext": "SERENITY 95 m² Außenansicht",
        "alt.serenity_int": "SERENITY 95 m² Innenansicht",
        "page_label.PAGE 11": "SEITE 11",
        "p11.title": "SERENITY",
        "p11.subtitle_short": "95 m² • 3 Schlafzimmer",
        "p11.subtitle_long": "Großzügiger Komfort für kleine Familien. Offener Grundriss mit viel Weite bei hoher Effizienz.",
        "price.value.serenity.semi": "109.800 €",
        "price.value.serenity.turnkey": "189.800 €",
        "alt.floorplan_95": "Grundriss 95 m²",
        "dims.value.serenity.living_kitchen": "32,61 m²",
        "dims.value.serenity.bed1": "12,33 m²",
        "dims.value.serenity.bed2": "11,82 m²",
        "dims.value.serenity.bed3": "11,82 m²",
        "dims.value.serenity.bath1": "4,63 m²",
        "dims.value.serenity.bath2": "3,77 m²",
        "dims.value.serenity.interior": "11,80 m × 6,80 m × 2,50 m",
        "dims.value.serenity.exterior": "12,60 m × 7,60 m × 3,20 m",
        "page_label.PAGE 12": "SEITE 12",
        "finish.price.serenity.cashmere.semi": "Ausbauhaus: 7.800 €",
        "finish.price.serenity.cashmere.tk": "Schlüsselfertig: Inklusive",
        "finish.price.serenity.hazelnut.semi": "Ausbauhaus: 7.800 €",
        "finish.price.serenity.hazelnut.tk": "Schlüsselfertig: Inklusive",
        "finish.price.serenity.yakisugi.choose": "Wunschfassade wählen",
        "finish.price.serenity.lunawood.choose": "Wunschfassade wählen",
        "upgrade.price.serenity.ventilation.semi": "Ausbauhaus: 9.800 €",
        "upgrade.price.serenity.ventilation.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.serenity.blinds.semi": "Ausbauhaus: 7.000 €",
        "upgrade.price.serenity.blinds.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.serenity.solar": "14.800 €",
        "upgrade.note.serenity.solar": "Erzeugt 60 % mehr Energie als der jährliche Verbrauch",
        "page_label.PAGE 13": "SEITE 13",
        "house.sanctuary": "SANCTUARY",
        "alt.sanctuary_ext": "SANCTUARY 142 m² Außenansicht",
        "alt.sanctuary_int": "SANCTUARY 142 m² Innenansicht",
        "page_label.PAGE 14": "SEITE 14",
        "p14.title": "SANCTUARY",
        "p14.subtitle_short": "142 m² • 4 Schlafzimmer",
        "p14.subtitle_long": "Luxuriöses Familienleben mit vier großzügigen Schlafzimmern. Das Optimum nachhaltigen Wohnens für wachsende Familien.",
        "price.value.sanctuary.semi": "159.800 €",
        "price.value.sanctuary.turnkey": "279.800 €",
        "alt.floorplan_142": "Grundriss 142 m²",
        "dims.value.sanctuary.living_kitchen": "62,90 m²",
        "dims.value.sanctuary.bed1": "12,40 m²",
        "dims.value.sanctuary.bed2": "12,20 m²",
        "dims.value.sanctuary.bed3": "12,40 m²",
        "dims.value.sanctuary.bed4": "13,10 m²",
        "dims.value.sanctuary.bath1": "3,75 m²",
        "dims.value.sanctuary.bath2": "4,35 m²",
        "dims.value.sanctuary.interior": "11,80 m × 10,60 m × 2,50 m",
        "dims.value.sanctuary.exterior": "12,60 m × 11,30 m × 3,20 m",
        "page_label.PAGE 15": "SEITE 15",
        "finish.price.sanctuary.cashmere.semi": "Ausbauhaus: 11.800 €",
        "finish.price.sanctuary.cashmere.tk": "Schlüsselfertig: Inklusive",
        "finish.price.sanctuary.hazelnut.semi": "Ausbauhaus: 11.800 €",
        "finish.price.sanctuary.hazelnut.tk": "Schlüsselfertig: Inklusive",
        "finish.price.sanctuary.yakisugi.choose": "Wunschfassade wählen",
        "finish.price.sanctuary.lunawood.choose": "Wunschfassade wählen",
        "upgrade.price.sanctuary.ventilation.semi": "Ausbauhaus: 9.800 €",
        "upgrade.price.sanctuary.ventilation.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.sanctuary.blinds.semi": "Ausbauhaus: 9.000 €",
        "upgrade.price.sanctuary.blinds.tk": "Schlüsselfertig: Inklusive",
        "upgrade.price.sanctuary.solar": "16.800 €",
        "upgrade.note.sanctuary.solar": "Erzeugt 60 % mehr Energie als der jährliche Verbrauch",
        "page_label.PAGE 16": "SEITE 16",
        "contact.h1": "Lassen Sie uns\nIhre Zukunft bauen",
        "contact.tagline_line1": "Bereit für Ihr nachhaltiges Zuhause?",
        "contact.tagline_line2": "Kontaktieren Sie noch heute unser Team.",
        "contact.footer": "BIOBUILDS MODULAR • 2026"
    },
    ro: {
        "head.title": "Catalog complet BIOBUILDS 2026",
        "cover.vertical_text": "Născut din natură, construit pentru viață",
        "brand.name": "BIOBUILDS",
        "brand.module_label": "BIOBUILDS MODULAR",
        "cover.h1_line1": "Mai mult decât o casă",
        "cover.h1_line2": "un mod de viață",
        "cover.tagline": "Viața sustenabilă redefinită",
        "year.2026": "2026",
        "contact.email": "hello@biobuilds.com",
        "contact.domain": "biobuilds.com",
        "page_label.PAGE 1": "PAGINA 1",
        "p1.h2": "De la natură la excelență",
        "p1.intro": "Sistemul nostru de pereți de 386 mm combină materiale sustenabile cu tehnologie de ultimă generație, obținând performanță termică excepțională și etanșeitate ridicată într-un mediu natural de locuire.",
        "spec.steico.title": "Fibră de lemn STEICO",
        "spec.steico.desc": "Izolație naturală din fibră de lemn de 300 mm, ultra-performantă.",
        "spec.membrane.title": "Membrană inteligentă",
        "spec.membrane.desc": "Barieră permeabilă la vapori care permite pereților să 'respire'.",
        "spec.osb.title": "OSB ECO din Germania",
        "spec.osb.desc": "Fără formaldehidă, pentru un mediu interior sănătos",
        "spec.structure.title": "Structură certificată",
        "spec.structure.desc": "Structură brevetată din lemn C24, certificată de Passivhaus Institut",
        "alt.epd_logo": "Certificare EPD",
        "alt.passivhaus_logo": "Certificare Passivhaus",
        "alt.wall_section": "Secțiune perete",
        "page_label.PAGE 2": "PAGINA 2",
        "p2.title": "SEMI-FINISAT",
        "p2.subtitle": "Casa BIOBUILDS semi-finisat: fii propriul tău designer. Exterior complet finalizat, interior pregătit pentru viziunea ta.",
        "p2.section.interior": "Interior",
        "p2.interior.item1": "Structură MODULAR™ ~35 cm, certificat Passivhaus / EPD. Sistem timber-frame volumetric cu izolație SteicoFLEX, placare fibră de lemn, membrană inteligentă și strat continuu OSB. Fără punți termice. Complet etanș.",
        "p2.interior.item2": "Băi hidroizolate cu instalații la locul lor",
        "p2.interior.item3": "Pregătită pentru designul și finisajele tale personalizate",
        "p2.section.exterior": "Exterior",
        "p2.exterior.lead": "Exterior complet finalizat:",
        "p2.exterior.item1": "Structură certificată Passivhaus: MODULAR",
        "p2.exterior.item2": "Finisaj natural Yakisugi/Lunawood",
        "p2.exterior.item3": "Acoperiș plat ventilat cu membrană EPDM",
        "p2.exterior.item4": "Sistem integrat de colectare a apei pluviale",
        "p2.exterior.item5": "Ferestre tripan, cadru din aluminiu Genesis 90",
        "p2.section.installations": "Instalații",
        "p2.installations.item1": "Instalație electrică complet pregătită (conform normelor UE)",
        "p2.installations.item2": "Instalație sanitară complet pregătită (conform normelor UE)",
        "p2.installations.item3": "Puncte pregătite pentru bucătărie (pentru mobilier și electrocasnice)",
        "p2.section.docs": "Documentație",
        "p2.docs.item1": "Certificare Passivhaus",
        "p2.docs.item2": "Documentație de sustenabilitate EPD",
        "p2.docs.item3": "Marcaj CE pentru toate componentele relevante",
        "p2.docs.item4": "Garanție 24 luni (rezidențial), 12 luni (comercial)",
        "page_label.PAGE 3": "PAGINA 3",
        "p3.title": "LA CHEIE",
        "p3.subtitle": "Totul inclus: exterior, interior, sisteme inteligente și mult mai mult.",
        "p3.section.interior": "Interior",
        "p3.interior.lead": "Totul din Semi-finisat plus:",
        "p3.interior.item1": "Tavane din lamele de lemn natural cu pâslă reciclată",
        "p3.interior.item2": "Finisaje de perete din catalogul nostru: fibră de sticlă, pâslă, furnir de lemn etc.",
        "p3.interior.item3": "Parchet triplu stratificat 9–14 mm, certificat FSC, finisaj durabil",
        "p3.interior.item4": "Uși interioare S10 cu fagure (certificate CE)",
        "p3.interior.item5": "Prize premium Schneider (certificate CE/VDE)",
        "p3.section.exterior": "Exterior",
        "p3.exterior.lead": "Exterior complet finalizat:",
        "p3.exterior.item1": "Structură certificată Passivhaus: MODULAR",
        "p3.exterior.item2": "Fațadă organică Yakisugi/Lunawood",
        "p3.exterior.item3": "Acoperiș plat ventilat cu membrană EPDM",
        "p3.exterior.item4": "Sistem integrat de colectare a apei pluviale",
        "p3.exterior.item5": "Ferestre Tripan, cadru din aluminiu Genesis 90",
        "p3.section.installations": "Instalații",
        "p3.installations.lead": "Totul din varianta Semi-finisat PLUS:",
        "p3.installations.item1": "Baie complet utilată: plăci compozit de marmură, chiuvetă italiană, WC încastrat Grohe, duș walk-in",
        "p3.installations.item2": "Boiler Ariston Velis (design ultra-subțire)",
        "p3.installations.item3": "Iluminat inteligent (Philips HUE sau IKEA TRÅDFRI)",
        "p3.installations.item4": "Jaluzele exterioare inteligente",
        "p3.installations.item5": "Sistem de ventilație Zehnder + Pompă de căldură Panasonic",
        "p3.section.docs": "Documentație",
        "p3.docs.item1": "Certificare Passivhaus",
        "p3.docs.item2": "Documentație de sustenabilitate EPD",
        "p3.docs.item3": "Marcaj CE pentru toate componentele relevante",
        "p3.docs.item4": "Garanție 24 luni (rezidențial), 12 luni (comercial)",
        "page_label.PAGE 4": "PAGINA 4",
        "house.nest": "NEST",
        "alt.nest_ext": "NEST 24 m² Exterior",
        "alt.nest_int": "NEST 24 m² Interior",
        "page_label.PAGE 5": "PAGINA 5",
        "p5.title": "NEST",
        "p5.subtitle_short": "24 m² • 1 dormitor",
        "p5.subtitle_long_line1": "Conceptul de tiny house, complet reinventat.",
        "p5.subtitle_long_line2": "Ideal pentru turism sau un stil de viață minimalist și contemporan.",
        "price.label.semi": "Semi-finisat",
        "price.label.turnkey": "La cheie",
        "price.value.nest.semi": "39.800 €",
        "price.value.nest.turnkey": "59.800 €",
        "alt.floorplan_24": "Plan parter 24 m²",
        "dims.title": "Dimensiuni",
        "dims.label.bedroom": "Dormitor",
        "dims.label.bathroom": "Baie",
        "dims.label.interior": "Interior",
        "dims.label.exterior": "Exterior",
        "dims.value.nest.bedroom": "14,20 m²",
        "dims.value.nest.bathroom": "3,45 m²",
        "dims.value.nest.interior": "5,70 m × 3,10 m × 2,50 m",
        "dims.value.nest.exterior": "6,40 m × 3,80 m × 3,20 m",
        "page_label.PAGE 6": "PAGINA 6",
        "upgrades.title": "OPȚIUNI SUPLIMENTARE",
        "finish.cashmere": "Cashmere",
        "finish.hazelnut": "Hazelnut",
        "finish.price.nest.cashmere.semi": "Semi-finisat: 1.800 €",
        "finish.price.nest.cashmere.tk": "La cheie: inclus",
        "finish.price.nest.hazelnut.semi": "Semi-finisat: 1.800 €",
        "finish.price.nest.hazelnut.tk": "La cheie: inclus",
        "cladding.yakisugi": "Yakisugi",
        "cladding.lunawood": "Lunawood",
        "cladding.choose": "Alege finisajul exterior",
        "upgrade.ventilation": "Sistem de ventilație",
        "upgrade.blinds": "Jaluzele inteligente",
        "upgrade.solar": "Kit solar Zero Energy",
        "upgrade.price.nest.ventilation.semi": "Semi-finisat: 4.800 €",
        "upgrade.price.nest.ventilation.tk": "La cheie: inclus",
        "upgrade.price.nest.blinds.semi": "Semi-finisat: 2.000 €",
        "upgrade.price.nest.blinds.tk": "La cheie: inclus",
        "upgrade.price.nest.solar": "7.800 €",
        "upgrade.note.solar": "Produce cu 60% mai multă energie decât consumul anual",
        "upgrade.ventilation.disclaimer": "Sistemul de ventilație Zehnder variază în funcție de dimensiunea modulului",
        "page_label.PAGE 7": "PAGINA 7",
        "house.wanderlust": "WANDERLUST",
        "alt.wanderlust_ext": "WANDERLUST 48 m² Exterior",
        "alt.wanderlust_int": "WANDERLUST 48 m² Interior",
        "page_label.PAGE 8": "PAGINA 8",
        "p8.title": "WANDERLUST",
        "p8.subtitle_short": "48 m² • 1 dormitor",
        "p8.subtitle_long": "Perfectă pentru cupluri sau ca reședință de vacanță. Combină confortul cu eficiența într-un spațiu bine gândit.",
        "price.value.wanderlust.semi": "59.800 €",
        "price.value.wanderlust.turnkey": "109.800 €",
        "alt.floorplan_48": "Plan parter 48 m²",
        "dims.label.living_kitchen": "Living + Bucătărie",
        "dims.value.wanderlust.living_kitchen": "19,90 m²",
        "dims.value.wanderlust.bedroom": "11,80 m²",
        "dims.value.wanderlust.bathroom": "4,50 m²",
        "dims.value.wanderlust.interior": "11,60 m × 3,10 m × 2,50 m",
        "dims.value.wanderlust.exterior": "12,40 m × 3,80 m × 3,20 m",
        "page_label.PAGE 9": "PAGINA 9",
        "finish.price.wanderlust.cashmere.semi": "Semi-finisat: 3.800 €",
        "finish.price.wanderlust.cashmere.tk": "La cheie: inclus",
        "finish.price.wanderlust.hazelnut.semi": "Semi-finisat: 3.800 €",
        "finish.price.wanderlust.hazelnut.tk": "La cheie: inclus",
        "upgrade.price.wanderlust.ventilation.semi": "Semi-finisat: 7.800 €",
        "upgrade.price.wanderlust.ventilation.tk": "La cheie: inclus",
        "upgrade.price.wanderlust.blinds.semi": "Semi-finisat: 4.000 €",
        "upgrade.price.wanderlust.blinds.tk": "La cheie: inclus",
        "upgrade.price.wanderlust.solar": "11.800 €",
        "upgrade.note.wanderlust.solar": "Produce cu 60% mai multă energie decât consumul anual",
        "page_label.PAGE 10": "PAGINA 10",
        "house.serenity": "SERENITY",
        "alt.serenity_ext": "SERENITY 95 m² Exterior",
        "alt.serenity_int": "SERENITY 95 m² Interior",
        "page_label.PAGE 11": "PAGINA 11",
        "p11.title": "SERENITY",
        "p11.subtitle_short": "95 m² • 3 dormitoare",
        "p11.subtitle_long": "Confort generos pentru familii mici. Design deschis care oferă spațiu și eficiență în același timp.",
        "price.value.serenity.semi": "109.800 €",
        "price.value.serenity.turnkey": "189.800 €",
        "alt.floorplan_95": "Plan parter 95 m²",
        "dims.value.serenity.living_kitchen": "32,61 m²",
        "dims.value.serenity.bed1": "12,33 m²",
        "dims.value.serenity.bed2": "11,82 m²",
        "dims.value.serenity.bed3": "11,82 m²",
        "dims.value.serenity.bath1": "4,63 m²",
        "dims.value.serenity.bath2": "3,77 m²",
        "dims.value.serenity.interior": "11,80 m × 6,80 m × 2,50 m",
        "dims.value.serenity.exterior": "12,60 m × 7,60 m × 3,20 m",
        "page_label.PAGE 12": "PAGINA 12",
        "finish.price.serenity.cashmere.semi": "Semi-finisat: 7.800 €",
        "finish.price.serenity.cashmere.tk": "La cheie: inclus",
        "finish.price.serenity.hazelnut.semi": "Semi-finisat: 7.800 €",
        "finish.price.serenity.hazelnut.tk": "La cheie: inclus",
        "finish.price.serenity.yakisugi.choose": "Alege finisajul exterior",
        "finish.price.serenity.lunawood.choose": "Alege finisajul exterior",
        "upgrade.price.serenity.ventilation.semi": "Semi-finisat: 9.800 €",
        "upgrade.price.serenity.ventilation.tk": "La cheie: inclus",
        "upgrade.price.serenity.blinds.semi": "Semi-finisat: 7.000 €",
        "upgrade.price.serenity.blinds.tk": "La cheie: inclus",
        "upgrade.price.serenity.solar": "14.800 €",
        "upgrade.note.serenity.solar": "Produce cu 60% mai multă energie decât consumul anual",
        "page_label.PAGE 13": "PAGINA 13",
        "house.sanctuary": "SANCTUARY",
        "alt.sanctuary_ext": "SANCTUARY 142 m² Exterior",
        "alt.sanctuary_int": "SANCTUARY 142 m² Interior",
        "page_label.PAGE 14": "PAGINA 14",
        "p14.title": "SANCTUARY",
        "p14.subtitle_short": "142 m² • 4 dormitoare",
        "p14.subtitle_long": "Locuință de familie luxoasă, cu patru dormitoare spațioase. Standardul suprem al designului sustenabil pentru familiile moderne.",
        "price.value.sanctuary.semi": "159.800 €",
        "price.value.sanctuary.turnkey": "279.800 €",
        "alt.floorplan_142": "Plan parter 142 m²",
        "dims.value.sanctuary.living_kitchen": "62,90 m²",
        "dims.value.sanctuary.bed1": "12,40 m²",
        "dims.value.sanctuary.bed2": "12,20 m²",
        "dims.value.sanctuary.bed3": "12,40 m²",
        "dims.value.sanctuary.bed4": "13,10 m²",
        "dims.value.sanctuary.bath1": "3,75 m²",
        "dims.value.sanctuary.bath2": "4,35 m²",
        "dims.value.sanctuary.interior": "11,80 m × 10,60 m × 2,50 m",
        "dims.value.sanctuary.exterior": "12,60 m × 11,30 m × 3,20 m",
        "page_label.PAGE 15": "PAGINA 15",
        "finish.price.sanctuary.cashmere.semi": "Semi-finisat: 11.800 €",
        "finish.price.sanctuary.cashmere.tk": "La cheie: inclus",
        "finish.price.sanctuary.hazelnut.semi": "Semi-finisat: 11.800 €",
        "finish.price.sanctuary.hazelnut.tk": "La cheie: inclus",
        "finish.price.sanctuary.yakisugi.choose": "Alege finisajul exterior",
        "finish.price.sanctuary.lunawood.choose": "Alege finisajul exterior",
        "upgrade.price.sanctuary.ventilation.semi": "Semi-finisat: 9.800 €",
        "upgrade.price.sanctuary.ventilation.tk": "La cheie: inclus",
        "upgrade.price.sanctuary.blinds.semi": "Semi-finisat: 9.000 €",
        "upgrade.price.sanctuary.blinds.tk": "La cheie: inclus",
        "upgrade.price.sanctuary.solar": "16.800 €",
        "upgrade.note.sanctuary.solar": "Produce cu 60% mai multă energie decât consumul anual",
        "page_label.PAGE 16": "PAGINA 16",
        "contact.h1": "Haide să construim\nviitorul tău",
        "contact.tagline_line1": "Pregătit pentru locuința ta sustenabilă?",
        "contact.tagline_line2": "Contactează echipa noastră astăzi.",
        "contact.footer": "BIOBUILDS MODULAR • 2026"
    }
};

// Language switching function - assign to window immediately
window.switchLanguage = function(lang) {
    console.log('[v0] Switching to language:', lang);

    // Update active button
    document.querySelectorAll('.language-selector button').forEach(btn => {
        btn.classList.remove('active');
    });
    const targetBtn = document.getElementById('lang-' + lang);
    if (targetBtn) {
        targetBtn.classList.add('active');
    }

    // Update text content
    if (lang === 'en') {
        // Store EN preference and reload to reset to English
        localStorage.setItem('catalogLanguage', 'en');
        location.reload();
        return;
    }

    const langData = translations[lang];
    if (!langData) {
        console.error('[v0] Language data not found for:', lang);
        return;
    }

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (langData[key]) {
            // Handle line breaks in translations
            if (langData[key].includes('\n')) {
                el.innerHTML = langData[key].replace(/\n/g, '<br>');
            } else {
                el.textContent = langData[key];
            }
        }
    });

    // Update alt attributes
    document.querySelectorAll('[data-i18n-alt]').forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (langData[key]) {
            el.setAttribute('alt', langData[key]);
        }
    });

    // Update document title
    if (langData['head.title']) {
        document.title = langData['head.title'];
    }

    // Store language preference
    localStorage.setItem('catalogLanguage', lang);
    console.log('[v0] Language switched successfully to:', lang);
};

// Load saved language on page load
document.addEventListener('DOMContentLoaded', function() {
    console.log('[v0] DOM loaded, checking saved language');
    const savedLang = localStorage.getItem('catalogLanguage');
    if (savedLang && savedLang !== 'en') {
        console.log('[v0] Restoring saved language:', savedLang);
        window.switchLanguage(savedLang);
    }
});
